### ISSUE TITLE
prefabs

### ISSUE THREAD

**Issue by mreinstein** [mreinstein/substrate-builder#6]
being able to take a node from the scene and make it re-usable/instantiable. Should probably show up in some kind of expando list.

**Comment by marcantoupin** [comment]
Here's how I see it:
- Have a "make prefab" button to turn a given node into a prefab
- Have a "make unique" button to turn back an instance of a prefab into an independent node
- From that point, the node is copied into the "prefabs" tree from which it can be dragged/dropped on the scene/in the scene tree. That clones it, preserving the original in the prefabs tree.
- To edit a prefab's properties, we use the same properties panel as for regular nodes, by selecting either the prefab in the prefabs tree, or an instance of it. When a property is changed the change is reflected immediately on all instances of the prefab and the original.
- Adding/removing scripts on a prefab or an instance of it would also have to be reflected on all instances. That might be one of the most tricky part I think. We could choose not to display scripts as children of instances in the scene tree, only show them in the prefabs tree
- To indicate that a node is a prefab, its name could be displayed in a different color

**Comment by mreinstein** [comment]
Sounds reasonable 👍 

> Adding/removing scripts on a prefab or an instance of it would also have to be reflected on 
> all instances. That might be one of the most tricky part I think. We could choose not to 
> display scripts as children of instances in the scene tree, only show them in the prefabs tree

One way we might solve this: we could choose to not display any sub-children of a node which is a prefab instance. You also wouldn't be able to drop children onto a prefab. An example:

```
root
  |- 📦node 1
  |- node 2
  |    |- child node
  |    |- ⚙ script component
  |    `- child node
  |         |- ⚙ script component
  |         `- ⚙ another script component
  `- node 3
```

`node2` and `node3` would be regular substrate nodes, with children, optional script nodes, etc. `node1` would be an instance of a prefab. The prefab might have a number of sub children, included scripts, etc. but you wouldn't see them because this would basically be an instance.

This is just an idea, open for suggestions!

**Comment by mreinstein** [comment]
>  the node is copied into the "prefabs" tree from which it can be dragged/dropped 
> on the scene/in the scene tree

I assume the `"prefabs" tree` would always be flat with no children, and basically just be a list>

**Comment by mreinstein** [comment]
ohhh wait, ignore my last comment. After re-reading this:

> Adding/removing scripts on a prefab or an instance of it would also have to be 
> reflected on all instances. That might be one of the most tricky part I think. 
> We could choose not to display scripts as children of instances in the scene 
> tree, only show them in the prefabs tree

So the prefab tree would *not* always be flat with no children, this would be an editable tree, and changing the nodes in this tree would update all prefab instances. Is that accurate?

**Comment by marcantoupin** [comment]
Yes, that's the idea! And I agree with the scene tree not displaying children/scripts of prefab instances.
